version: 0.2

env:
  variables:
    NODE_ENV: "${env}"
    REACT_APP_MAP_LEAFLET_ID: "${REACT_APP_MAP_LEAFLET_ID}"
    REACT_APP_MAP_LEAFLET_KEY: "${REACT_APP_MAP_LEAFLET_KEY}"

  parameter-store:
    REACT_APP_MAP_LEAFLET_ID: REACT_APP_MAP_LEAFLET_ID
    REACT_APP_MAP_LEAFLET_KEY: REACT_APP_MAP_LEAFLET_KEY
  exported-variables:
    - REACT_APP_MAP_LEAFLET_KEY
    - REACT_APP_MAP_LEAFLET_ID

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo printenv
      - yarn install
  pre_build:
    commands:
      - echo Mot Running tests . . .
      # - CI=true yarn test
      - echo Tests complete
      
  build:
    commands:
      - echo Checking Environment Variables
      - echo cfdistid - $REACT_APP_MAP_LEAFLET_ID
      - echo ls
      
      - echo Starting build . . .
      # - export BUCKET_PREFIX=$LAMBDA_PKG_BUCKET_PREFIX
      - yarn run build

artifacts:
  files:
    - '**/*'
  name: "web-dist-$(date +%Y-%m-%d)"
  base-directory: build

cache:
  paths:
    - /root/.npm/**/*
